/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.testService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TestNotice service. Represents a row in the &quot;liferay_db_TestNotice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.testService.model.impl.TestNoticeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.testService.model.impl.TestNoticeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TestNotice
 * @generated
 */
@ProviderType
public interface TestNoticeModel extends BaseModel<TestNotice> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test notice model instance should use the {@link TestNotice} interface instead.
	 */

	/**
	 * Returns the primary key of this test notice.
	 *
	 * @return the primary key of this test notice
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test notice.
	 *
	 * @param primaryKey the primary key of this test notice
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the notice ID of this test notice.
	 *
	 * @return the notice ID of this test notice
	 */
	public long getNoticeId();

	/**
	 * Sets the notice ID of this test notice.
	 *
	 * @param noticeId the notice ID of this test notice
	 */
	public void setNoticeId(long noticeId);

	/**
	 * Returns the notice text of this test notice.
	 *
	 * @return the notice text of this test notice
	 */
	@AutoEscape
	public String getNoticeText();

	/**
	 * Sets the notice text of this test notice.
	 *
	 * @param noticeText the notice text of this test notice
	 */
	public void setNoticeText(String noticeText);

	/**
	 * Returns the owner ID of this test notice.
	 *
	 * @return the owner ID of this test notice
	 */
	public long getOwnerId();

	/**
	 * Sets the owner ID of this test notice.
	 *
	 * @param ownerId the owner ID of this test notice
	 */
	public void setOwnerId(long ownerId);

}