/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.testService.model.impl;

import com.testService.model.TestUser;
import com.testService.service.TestUserLocalServiceUtil;

/**
 * The extended model base implementation for the TestUser service. Represents a row in the &quot;liferay_db_TestUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TestUserImpl
 * @see TestUser
 * @generated
 */
public abstract class TestUserBaseImpl
	extends TestUserModelImpl implements TestUser {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a test user model instance should use the <code>TestUser</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TestUserLocalServiceUtil.addTestUser(this);
		}
		else {
			TestUserLocalServiceUtil.updateTestUser(this);
		}
	}

}